if username not given

diff --git a/create b/create
--- a/create
+++ b/create
@@ -5,21 +5,28 @@
 #You can't read /etc/shadow
 #You can't directly modify /etc/passwd
 
-if [ $(id -u) -eq 0 ]; then
-	read -p "Enter username : " username
-	read -s -p "Enter password : " password
-	egrep "^$username" /etc/passwd >/dev/null
-	if [ $? -eq 0 ]; then
-		echo -e "\n$username exists!"
-		#exit 1
+if [[ -n $3 ]]
+then
+	if [ $(id -u) -eq 0 ]
+	then
+		#read -p "Enter username : " username
+		read -s -p "Enter password : " password
+		egrep "^$username" /etc/passwd >/dev/null
+			if [ $? -eq 0 ]
+			then
+				echo -e "\n$username exists!"
+				#exit 1
+			else
+				pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
+				useradd -s /bin/bash -m -p "$pass" "$username"
+				[ $? -eq 0 ] && echo "User has been added to system!" || echo "Failed to add a user!"
+			fi
 	else
-		pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
-		useradd -s /bin/bash -m -p "$pass" "$username"
-		[ $? -eq 0 ] && echo "User has been added to system!" || echo "Failed to add a user!"
+		echo "Only root may add a user to the system."
+		#exit 2
 	fi
 else
-	echo "Only root may add a user to the system."
-	#exit 2
+	echo "Write Username also"
 fi
 
 
