changes

diff --git a/Command/internsctl b/Command/internsctl
--- a/Command/internsctl
+++ b/Command/internsctl
@@ -25,16 +25,18 @@ create() {
 		then
 			read -r -s -p "Enter password : " password
 			grep -E "^$3" /etc/passwd >/dev/null
-				if [ $? -eq 0 ]
+				if [[ $? -eq 0 ]]
 				then
 					echo -e "\n$3 exists!"
+					exit 1
 				else
 					pass=$(perl -e 'print crypt($ARGV[0], "password")' "$password")
-					useradd -s /bin/bash -m -p "$pass" "$(username)"
-					[ $? -eq 0 ] && echo "User has been added to system!" || echo "Failed to add a user!"
+					useradd -s /bin/bash -m -p "$pass" "$3"
+					[ $? -eq 0 ] && echo -e "\nUser has been added to system!" || echo "Failed to add a user!"
 				fi
 		else
 			echo "Only root can add a user to the system."
+			exit 2
 		fi
 	else
 		echo "Write Username also"
